# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages

frontend:
  themes: !include_dir_merge_named themes/

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  server_port: !secret server_port
  ssl_certificate: !secret ssl_cert_dir
  ssl_key: !secret ssl_key_dir
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5
    
group: !include groups.yaml
automation: !include automations.yaml
scene: !include scenes.yaml
switch: !include switch.yaml
sensor: !include_dir_merge_list sensors/
script: !include_dir_named scripts/


# Lovelace Control
lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml

# iOS Preparations
ios:

# New Discovery
discovery: