# Android Sensor
- platform: template
  sensors:
    oneplus_battery_sensor:
      entity_id: device_tracker.hd1910
      value_template: "{{ state_attr('device_tracker.hd1910', 'battery_level')|int|default(0) }}"
      device_class: battery
      unit_of_measurement: '%'